version: '3'
services:
  fastapi:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    env_file:
      - ./app/.env
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=2298367600
      - POSTGRES_DB=postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: